# Generated by Django 3.1.1 on 2021-01-29 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_files',
            name='image',
            field=models.FilePathField(path='demo_main/demo_app/static/img/project1.png'),
        ),
    ]
