# Generated by Django 3.1.1 on 2021-01-29 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo_app', '0002_auto_20210129_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv_files',
            name='image',
            field=models.FilePathField(path='/img'),
        ),
    ]
